### ISSUE TITLE
Aquamacs.download.recipe producting 404 - just update Aquamacs.munki.recipe to use hansen-m's Aquamacs.download.recipe?

### ISSUE THREAD

**Issue by jakerundall** [mkuron/mkuron-recipes#1]
Good morning,

I just tried to use your Aquamacs Munki and download recipes.  The Aquamacs.download.recipe produces a 404 error, as follows:
MYPROMPT$ autopkg run -v Aquamacs.munki MakeCatalogs.munki
Processing Aquamacs.munki...
GitHubReleasesInfoProvider
GitHubReleasesInfoProvider: Selected asset 'Aquamacs-Emacs-3.2.dmg' from release 'Aquamacs Emacs 3.2'
URLDownloader
Couldn't download https://github.com/davidswelt/aquamacs-emacs/releases/download/Aquamacs-3.2/Aquamacs-Emacs-3.2.dmg: HTTP Error 404: Not Found
Failed.
Receipt written to /Users/rundall/Library/AutoPkg/Cache/local.munki.Aquamacs/receipts/Aquamacs-receipt-20151109-112341.plist
Processing MakeCatalogs.munki...
MakeCatalogsProcessor
MakeCatalogsProcessor: No need to rebuild catalogs.
Receipt written to /Users/rundall/Library/AutoPkg/Cache/com.github.autopkg.munki.makecatalogs/receipts/MakeCatalogs-receipt-20151109-112341.plist

The following recipes failed:
    Aquamacs.munki
        Error in local.munki.Aquamacs: Processor: URLDownloader: Error: Couldn't download https://github.com/davidswelt/aquamacs-emacs/releases/download/Aquamacs-3.2/Aquamacs-Emacs-3.2.dmg: HTTP Error 404: Not Found

Nothing downloaded, packaged or imported.

I found that hansen-m has a Aquamacs.download.recipe as well:https://github.com/autopkg/hansen-m-recipes/blob/master/Aquamacs/Aquamacs.download.recipe

Since it is already hosted in the autopkg git repo, I contacted the developer to see if they could get it fixed, and they did.

I then tested your Aquamacs.munki.recipe in conjunction with hansen-m's download recipe (changed the parent recipe to com.github.hansen-m.download.aquamacs).

Would you be willing to either:
(1) Update your Aquamacs.download.recipe in the same way that hansen-m did to fix the 404 issue?
OR
(2) Update your Aquamacs.munki.recipe to use hansen-m's Aquamacs.download.recipe?

I know that you haven't moved your recipes into the autopkg git repo, but I would definitely find your Aquamacs Munki recipe useful.  If you were to have it/them moved into the autopkg git repo, I believe it would show up when somebody does 'autopkg search aquamacs'.

Thanks!

Jake

**Comment by mkuron** [comment]
Here you go: 28ae651.

**Comment by jakerundall** [comment]
Thanks!
